name: go-ci

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./go
        run: make mod/download

      - name: Tools
        run: go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        working-directory: ./go
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 13306
          mysql version: 8.0
          mysql database: webapi
          mysql root password: P@ssw0rd

      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./go
        run: make mod/download

      - name: Tools
        run: |
          go install -v github.com/masakurapa/gover-html@latest
          go install -v github.com/pressly/goose/v3/cmd/goose@latest

      - name: Test & Cover
        working-directory: ./go
        run: make cover

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-coverage
          path: go/reports/coverage.html

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./go
        run: make mod/download

      - name: Build
        working-directory: ./go
        run: make build

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-bin
          path: go/bin/*
